spring.jpa.show-sql= true

spring.jpa.properties.hibernate.format-sql=true

#tells the Hibernate to wrap the table name in quotes so the database knows it's a table identifier, not a system keyword.
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# Enable L2 Cache
spring.jpa.properties.hibernate.cache.use_second_level_cache=true

#Tells hibernate to use Jcache as a caching region factory(SIP)
spring.jpa.properties.hibernate.cache.region.factory_class=jcache

#Enable Query-cache(L3) for custom query results
spring.jpa.properties.hibernate.cache.use_query_cache=true

